name: majkrzak/create-release
description: |
  Github Action for handling release creation
author: Piotr Majkrzak
branding:
  icon: box
  color: green
inputs:
  token:
    required: true
  name:
    required: true
  code:
    required: true
<<<<<<< HEAD
  body:
=======
  name: #Uploading Artifacts
    default: ''
  body: # Action performs 2 steps:
        # -Generate the artifacts
        # -Upload the artifacts
        # You can continue to work and add script 
        #.github/build to your repository, and configure this action with a pattern of files to upload.
>>>>>>> ced0b98... body
    default: ""
  prerelease:
    default: false
  recreate:
    default: false
  assets:
    defailt: ""
runs:
  using: node12
  main: action.js
